# Generated by Django 6.1 on 2026-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='accounts.skill'),
        ),
    ]
