# Generated by Django 6.1 on 2026-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_company_required_skills_job_required_skills'),
        ('resumes', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resumeanalysis',
            constraint=models.UniqueConstraint(fields=('resume', 'job'), name='unique_resume_job_analysis'),
        ),
    ]
